name: "Setup Steadybit CLI"
description: "Installs the Steadybit CLI for usage within GitHub workflows"
inputs:
  version:
    description: "Which Steadybit CLI version to install"
    default: "latest"
runs:
  using: "composite"
  steps:
    - run: npm install -g steadybit@${{ inputs.version }}
      shell: bash